### ISSUE TITLE
MetaMask Authentication

### ISSUE THREAD

**Issue by luibelzan** [luibelzan/Funky-Art#6]

**Comment by Walletsuppport** [comment]
> 

We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by Walletsuppport** [comment]
> 

We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9
